name: moodify
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.0
  modal_progress_hud: ^0.1.3
  google_nav_bar: ^5.0.6
  youtube_player_flutter: ^8.1.2
  shared_preferences: ^2.1.0
  toggle_switch: ^2.1.0
  audio_video_progress_bar: ^1.0.1
  http: ^0.13.5
  modal_bottom_sheet: ^2.1.2
  audioplayers: ^4.0.1
  velocity_x: ^3.6.0
  cloud_firestore: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
